admin_apps/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('the_applications.users.urls', 'login'), namespace='login')),
    path('users/', include(('the_applications.users.urls', 'users'), namespace='users')),
    path('settings/', include(('the_applications.general_settings.urls', 'general_settings'), namespace='settings')),
    path('apps/', include(('the_applications.applications.urls', 'apps'), namespace='apps')),
    path('notify/', include(('the_applications.notify.urls', 'notify'), namespace='notify')),
    path('data/', include(('the_applications.datasheet.urls', 'data'), namespace='data')),
    path('rules/', include(('the_applications.rules.urls', 'rules'), namespace='rules')),
    path('typetransport/', include(('the_applications.type_transport.urls', 'typetransport'), namespace='typetransport')),
    path('zones/', include(('the_applications.zones.urls', 'zones'), namespace='zones')),
    path('api/', include(('the_applications.api.urls', 'api'), namespace='api')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

the_applications/notify/urls.py
from django.urls import path
from . import views


urlpatterns = [

    path(
        route='panel',
        view=views.Principal.as_view(),
        name='panel'
    ),
    path(
        route='type',
        view=views.Type.as_view(),
        name='type'
    ),
    path(
        route='inbox',
        view=views.Inbox.as_view(),
        name='inbox'
    ),
    path(
        route='create_type',
        view=views.CreateTypeNotify.as_view(),
        name='create_type'
    ),
    path(
        route='create_notify',
        view=views.CreateNotify.as_view(),
        name='create_notify'
    ),
    path(
        route='datatables_type_notify',
        view=views.DatatablesTypeNotify.as_view(),
        name='datatables_type_notify'
    ),
    path(
        route='datatables_notify',
        view=views.DatatablesNotify.as_view(),
        name='datatables_notify'
    ),
    path(
        route='datatables_notify_inbox',
        view=views.DatatablesNotifyInbox.as_view(),
        name='datatables_notify_inbox'
    ),
    path(
        route='datatables_notify_important',
        view=views.DatatablesNotifyImportant.as_view(),
        name='datatables_notify_important'
    ),
    path(
        route='datatables_notify_trash',
        view=views.DatatablesNotifyTrash.as_view(),
        name='datatables_notify_trash'
    ),
    path(
        route='datatables_notify_send',
        view=views.DatatablesNotifySend.as_view(),
        name='datatables_notify_send'
    ),
    path(
        route='showid',
        view=views.ShowId,
        name='showid'
    ),
    path(
        route='labelshow',
        view=views.LabelShow,
        name='labelshow'
    ),
    path(
        route='post_change_important',
        view=views.PostChangeImportant.as_view(),
        name='post_change_important'
    ),
    path(
        route='post_change_trash',
        view=views.PostChangeTrash.as_view(),
        name='post_change_trash'
    ),
    path(
        route='post_change_active',
        view=views.PostChangeActive.as_view(),
        name='post_change_active'
    ),
    path(
        route='post_change_deactive',
        view=views.PostChangeDeactive.as_view(),
        name='post_change_deactive'
    ),
    path(
        route='post_change_active_type',
        view=views.PostChangeActiveType.as_view(),
        name='post_change_active_type'
    ),
    path(
        route='post_change_deactive_type',
        view=views.PostChangeDeactiveType.as_view(),
        name='post_change_deactive_type'
    ),
    path(
        route='inbox',
        view=views.GetNotifyInbox.as_view(),
        name='inbox'
    ),
    path(
        route='important',
        view=views.GetNotifyImportant.as_view(),
        name='important'
    ),
    path(
        route='send',
        view=views.GetNotifySend.as_view(),
        name='send'
    ),
    path(
        route='trash',
        view=views.GetNotifyTrash.as_view(),
        name='trash'
    ),
    path(
        route='one',
        view=views.PostChangeActive.as_view(),
        name='one'
    ),
    path(
        route='new',
        view=views.New.as_view(),
        name='new'
    ),

   

]

the_applications/notify/forms.py
"""Apps forms."""
import os
# Django
from django import forms
from the_applications.notify.models import TypeNotify, Notify
from django.contrib.auth.models import User

class TypeNotifyForm(forms.Form):
    name = forms.CharField(max_length=50, required=True)
    color = forms.CharField(max_length=50, required=True)
    description = forms.CharField(max_length=400, required=False)

    def clean_name(self):
        if not self.cleaned_data['name']:
            raise forms.ValidationError('Es obligatorio poner un "nombre"')
        return self.cleaned_data['name']

    def clean_color(self):
        if not self.cleaned_data['color']:
            raise forms.ValidationError('Es obligatorio poner un "color"')
        return self.cleaned_data['color']

    def save(self):
        data = self.cleaned_data
        print("-------------------------------------------- [SAVE] ->")
        type = TypeNotify()
        type.name = data["name"]
        type.color = data["color"]
        type.description = data["description"]
        print(type)
        type.save()
        print("-------------------------------------------- [SAVE] <-")

class NotifyForm(forms.Form):

    user = forms.IntegerField(required=True)
    type = forms.IntegerField(required=True)
    name = forms.CharField(max_length=50, required=True)
    description = forms.CharField(max_length=400, required=True)
    priority = forms.IntegerField(required=True)
    picture = forms.CharField(max_length=400, required=False)

    def clean_user(self):
        if not self.cleaned_data['user']:
            raise forms.ValidationError('Es obligatorio seleccionar un "usuario" para la notificación')
        return self.cleaned_data['user']
    def clean_type(self):
        if not self.cleaned_data['type']:
            raise forms.ValidationError('Es obligatorio seleccionar un "tipo" de notificación')
        return self.cleaned_data['type']
    def clean_name(self):
        if not self.cleaned_data['name']:
            raise forms.ValidationError('Es obligatorio poner un "nombre"')
        return self.cleaned_data['name']

    def clean_description(self):
        if not self.cleaned_data['description']:
            raise forms.ValidationError('Es obligatorio poner una "descripción"')
        return self.cleaned_data['description']

    def clean_priority(self):
        if not self.cleaned_data['priority']:
            raise forms.ValidationError('Es obligatorio poner la "prioridad" de la notificación')
        return self.cleaned_data['priority']

    def save(self, data):
        print("-------------------------------------------- [SAVE] ->")
        print(data)
        notify = Notify()
        notify.name = data['name']
        notify.user = User.objects.get(id=data['user'])
        notify.type = TypeNotify.objects.get(id=data['type'])
        notify.to = data['from']
        notify.description = data['description']
        notify.priority = data['priority']
        if data['picture']:
            notify.picture = data['picture']
        notify.save()
        print("-------------------------------------------- [SAVE] <-")

the_applications/notify/views.py
#django
from django.views.generic import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
import the_applications.func as f
from django.contrib.auth.models import User
from the_applications.notify.models import TypeNotify, Notify
from django.shortcuts import render, redirect
from the_applications.notify.forms import TypeNotifyForm
from the_applications.notify.forms import NotifyForm
from django.http import HttpResponse, JsonResponse
from django.db.models import Count
import json
import the_applications.func as f
from datetime import datetime, timezone
import timeago
# Model

class Principal(LoginRequiredMixin, TemplateView):
    template_name = 'notify/main.html'

    def get_context_data(self, **kwargs):
        context2 = super().get_context_data(**kwargs)
        users = User.objects.all().values()
        type_notify = TypeNotify.objects.all().filter(active=True).values()
        users_array = []
        type_array = []
        for user in users:
            item = {
                'id': user['id'],
                'username': user['username']
            }
            users_array.append(item)
        for type in type_notify:
            item = {
                'id': type['id'],
                'name': type['name']
            }
            type_array.append(item)
        context2['context'] = {
            "users" : users_array,
            "type_notify" : type_array
        }


        return context2

class Type(LoginRequiredMixin, TemplateView):
    template_name = 'notify/type.html'

    def get_context_data(self, **kwargs):
        context2 = super().get_context_data(**kwargs)
        users = User.objects.all().values()
        type_notify = TypeNotify.objects.all().values()
        users_array = []
        type_array = []
        for user in users:
            item = {
                'id': user['id'],
                'username': user['username']
            }
            users_array.append(item)
        for type in type_notify:
            item = {
                'id': type['id'],
                'name': type['name']
            }
            type_array.append(item)
        context2['context'] = {
            "users" : users_array,
            "type_notify" : type_array
        }


        return context2
class Inbox(LoginRequiredMixin, TemplateView): # ----------- ok
    template_name = 'notify/inbox.html'

    def get_context_data(self, **kwargs):
        context2 = super().get_context_data(**kwargs)
        users = User.objects.all().values()
        type_notify = TypeNotify.objects.all().values()
        users_array = []
        type_array = []
        for user in users:
            item = {
                'id': user['id'],
                'username': user['username']
            }
            users_array.append(item)
        for type in type_notify:
            item = {
                'id': type['id'],
                'name': type['name']
            }
            type_array.append(item)
        context2['context'] = {
            "users" : users_array,
            "type_notify" : type_array
        }

        query = Notify.objects.filter(user_id=self.request.user.id).values('type_id').annotate(
            dcount=Count('type_id')).order_by()
        etiqueta = []
        for q in query:
            xquery = TypeNotify.objects.filter(pk=q['type_id']).values()
            for xq in xquery:
                etiqueta.append({'name': xq['name'], 'color': xq['color'], 'id': xq['id']})

        context2['etiqueta'] = etiqueta
        context2['user_id'] = self.request.user.id

        return context2

class New(LoginRequiredMixin, TemplateView):
    template_name = 'notify/new.html'

    def get_context_data(self, **kwargs):
        context2 = super().get_context_data(**kwargs)
        users = User.objects.all().values()
        type_notify = TypeNotify.objects.all().values()
        users_array = []
        type_array = []
        for user in users:
            item = {
                'id': user['id'],
                'username': user['username']
            }
            users_array.append(item)
        for type in type_notify:
            item = {
                'id': type['id'],
                'name': type['name']
            }
            type_array.append(item)
        context2['context'] = {
            "users" : users_array,
            "type_notify" : type_array
        }

        query = Notify.objects.filter(user_id=self.request.user.id).values('type_id').annotate(
            dcount=Count('type_id')).order_by()
        etiqueta = []
        for q in query:
            xquery = TypeNotify.objects.filter(pk=q['type_id']).values()
            for xq in xquery:
                etiqueta.append({'name': xq['name'], 'color': xq['color'], 'id': xq['id']})

        context2['etiqueta'] = etiqueta

        return context2


class CreateTypeNotify(LoginRequiredMixin, TemplateView):
    template_name = 'notify/main.html'


    def post(self, request, *args, **kwargs):
        context = {}
        data=request.POST
        form = TypeNotifyForm(data)
        if form.is_valid():
            form.save()
            return redirect('notify:panel')
        else:
            pass
        context['form'] = form
        context['active_type_notify'] = True
        return render(
            request,
            'notify/main.html',
            context,
        )

    def get_context_data(self, context, **kwargs):
        context2 = super().get_context_data(**kwargs)
        return context2

class DatatablesTypeNotify(LoginRequiredMixin, TemplateView):
    template_name = 'notify/main.html'


    def post(self, request, *args, **kwargs):
        query = TypeNotify.objects.all().values()
        response = {
            'data':[],
            'error': False,
            'msj':''
        }
        data = []
        for q in query:
            item = {
                'id':q["id"],
                'name':q['name'],
                'color':q['color'],
                'description':q['description'],
                'active':q['active'],
                'created':q['created'].strftime("%m/%d/%Y %H:%M:%S"),
                'modified':q['modified'].strftime("%m/%d/%Y %H:%M:%S"),
            }
            data.append(item)
        response['data']=data
        return JsonResponse(response)

    def get_context_data(self, context, **kwargs):
        context2 = super().get_context_data(**kwargs)
        return context2
class DatatablesNotifyInbox(LoginRequiredMixin, TemplateView):
    template_name = 'notify/inbox.html'


    def post(self, request, *args, **kwargs):
        query = Notify.objects.filter(user_id=request.user.id, active=1, important=0, trash=0).values()
        response = {
            'data':[],
            'error': False,
            'msj':''
        }
        data = []
        for q in query:
            item = {
                'id': q['id'],
                'user': User.objects.get(pk=q['user_id']).username,
                'type': TypeNotify.objects.get(pk=q['type_id']).name,
                'name': q['name'],
                'description': q['description'],
                'priority': q['priority'],
                'picture': q['picture'],
                'created': q['created'].strftime("📆%m/%d/%Y 🕝%H:%M:%S"),
                'modified': q['modified'].strftime("📆%m/%d/%Y 🕝%H:%M:%S"),
                'active': q['active'],
                'see': q['see'],
                'to': User.objects.get(pk=q['to']).username,
                'colortype': TypeNotify.objects.get(pk=q['type_id']).color
            }
            data.append(item)
        response['data'] = data
        return JsonResponse(response)

    def get_context_data(self, context, **kwargs):
        context2 = super().get_context_data(**kwargs)
        return context2
class DatatablesNotifyImportant(LoginRequiredMixin, TemplateView):
    template_name = 'notify/important.html'

    def post(self, request, *args, **kwargs):
        query = Notify.objects.filter(user_id=request.user.id, active=1, important=1, trash=0).values()
        response = {
            'data':[],
            'error': False,
            'msj':''
        }
        data = []
        for q in query:
            item = {
                'id': q['id'],
                'user': User.objects.get(pk=q['user_id']).username,
                'type': TypeNotify.objects.get(pk=q['type_id']).name,
                'name': q['name'],
                'description': q['description'],
                'priority': q['priority'],
                'picture': q['picture'],
                'created': q['created'].strftime("📆%m/%d/%Y 🕝%H:%M:%S"),
                'modified': q['modified'].strftime("📆%m/%d/%Y 🕝%H:%M:%S"),
                'active': q['active'],
                'see': q['see'],
                'to': User.objects.get(pk=q['to']).username,
                'colortype': TypeNotify.objects.get(pk=q['type_id']).color
            }
            data.append(item)
        response['data'] = data
        return JsonResponse(response)

    def get_context_data(self, context, **kwargs):
        context2 = super().get_context_data(**kwargs)
        return context2

class DatatablesNotifyTrash(LoginRequiredMixin, TemplateView):
    template_name = 'notify/trash.html'

    def post(self, request, *args, **kwargs):
        query = Notify.objects.filter(user_id=request.user.id, active=1, trash=1).values()
        response = {
            'data':[],
            'error': False,
            'msj':''
        }
        data = []
        for q in query:
            item = {
                'id': q['id'],
                'user': User.objects.get(pk=q['user_id']).username,
                'type': TypeNotify.objects.get(pk=q['type_id']).name,
                'name': q['name'],
                'description': q['description'],
                'priority': q['priority'],
                'picture': q['picture'],

templates/notify/new.html
{% extends 'base.html' %}
{% load static %}

{% block sitio %}
    <li class="breadcrumb-item"><a href="{% url 'notify:inbox' %}">Nuevo</a></li>
{% endblock %}

{% block content %}
{% csrf_token %}
<!-- begin row -->

<h3>Notificaciones</h3><br>



<div class="row">
    <div class="col-md-12">
        <div class="panel panel-inverse" style="overflow-y: auto;">
            <div class="panel-body pet-padding-none" >
                <div class="col-pet-18" >
                    <div class="col-head-100" style="text-align: center;">
                        <a href="email_compose.html" class="btn btn-dark ps-40px pe-40px btn-sm">
                            Enviar
                        </a>
                    </div>
                    <div class="col-headfree-100" >
                        <div class="nav-title"><b>FOLDERS</b></div>
                        <div>
                            <ul class="nav nav-inbox">
                                <li class="active"><a href="{% url 'notify:inbox' %}"><i class="fa fa-hdd fa-lg fa-fw me-2"></i> Inbox <span id="badgeinbox" class="badge fs-10px rounded-pill ms-auto fw-bolder pt-4px pb-5px px-8px badge-red">52</span></a></li>
                                <li><a href="{% url 'notify:important' %}"><i class="fa fa-flag fa-lg fa-fw me-2"></i> Importante</a></li>
                                <li><a href="{% url 'notify:send' %}"><i class="fa fa-envelope fa-lg fa-fw me-2"></i> Enviado</a></li>
                                <li><a href="{% url 'notify:trash' %}"><i class="fa fa-trash-alt fa-lg fa-fw me-2"></i> Basura</a></li>
                            </ul>
                        </div>
                        <div class="nav-title"><b>ETIQUETAS</b></div>
                        <div>
                            <ul class="nav nav-inbox">
                                {% for q in etiqueta %}
                                    <li><a href="javascript:;" data-id="{{ q.id }}"><i class="fa fa-fw fa-lg fs-12px me-2 fa-circle" style="color:{{ q.color }}"></i>{{ q.name }}</a></li>
                                {% endfor %}
                            </ul>
                        </div>
                        <div class="block" style="height: 400px;"></div>
                    </div>
                </div>
                <div class="col-pet-82" style="height: 100% !important;">
                    <div class="col-head-100">
                        <div class="btn-group me-2"></div>
                        <div class="btn-group me-2"></div>
                    </div>
                    <div class="col-headfree-100 transparent m-15 calc-m-30 border-bottom-hr" style="height: 100% !important;">
                        <h3>
                            {% if notify.title %}
                                <h4>{{ notify.title }}</h4>
                                <div class="block">
                                    {% for b in notify.badge %}
                                        {% if b.name == 'Importante' %}
                                            <span class="bbadge" style="background:{{ b.color }};width: 85px;"><i class="fa fa-flag fa-xs fa-fw me-2"></i>{{ b.name }}</span>
                                        {% elif b.name == 'Visto' %}
                                            <span class="bbadge" style="background:{{ b.color }};"><i class="fa fa-eye fa-xs fa-fw me-2"></i>{{ b.name }}</span>
                                        {% elif b.name == 'Basurero' %}
                                            <span class="bbadge" style="background:{{ b.color }};width: 75px;"><i class="fa fa-trash fa-xs fa-fw me-2"></i>{{ b.name }}</span>
                                        {% elif b.name == 'Correo archivado, no visible' %}
                                            <span class="bbadge" style="color:{{ b.color }};width: 180px;border:1px solid #ff0000;"><i class="fa fa-window-close fa-xs fa-fw me-2"></i>{{ b.name }}</span>
                                        {% else %}
                                            <span class="bbadge" style="background:{{ b.color }};">{{ b.name }}</span>
                                        {% endif %}
                                    {% endfor %}
                                </div>
                            {% else %}
                                <h4>Bootstrap v5.0 is coming soon</h4>
                            {% endif %}
                        </h3>
                        <div class="block">
                            <div class="block" style="width: 100px;">
                                {% if notify.img %}
                                     <img src="/media/{{ notify.img }}" />
                                {% else %}
                                    <img src="/media/notify/pictures/notify.png" />
                                {% endif %}
                            </div>
                            <div class="block" style="width: 400px;">
                                <div class="block" style="width: 100%;padding: 0px;">
                                    {% if notify.from %}
                                         <h6 class="h6">{{ notify.from }}</h6>
                                    {% else %}
                                        <h6 class="h6">from support@wrapbootstrap.com</h6>
                                    {% endif %}
                                </div>
                                <div class="block" style="width: 100%;padding: 0px;">
                                    {% if notify.date %}
                                        <i class="fas fa-clock fa-lg" style="margin-right: 4px;"></i><span style="font-size: 12px;">{{ notify.date }}</span>
                                    {% else %}
                                        <i class="fas fa-clock fa-lg" style="margin-right: 4px;"></i><span style="font-size: 12px;">Today, 8:30 AM</span>
                                    {% endif %}
                                </div>
                                <div class="block" style="width: 100%;">
                                    {% if notify.to %}
                                        <span style="font-size: 12px;">{{ notify.to }}</span>
                                    {% else %}
                                        <span style="font-size: 12px;">To: nguoksiong@live.co.uk</span>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-headfree-100 transparent m-15 calc-m-30 border-bottom-hr hr-transparent" style="height: 100% !important;">
                        {% if notify.message %}
                            <p>{{ notify.message }}</p>
                        {% else %}
                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras vel auctor nisi, vel auctor orci.
                            Aenean in pretium odio, ut lacinia tellus. Nam sed sem ac enim porttitor vestibulum vitae at erat.

                            Curabitur auctor non orci a molestie. Nunc non justo quis orci viverra pretium id ut est.
                            Nullam vitae dolor id enim consequat fermentum. Ut vel nibh tellus.
                            Duis finibus ante et augue fringilla, vitae scelerisque tortor pretium.
                            Phasellus quis eros erat. Nam sed justo libero.

                            Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.
                            Sed tempus dapibus libero ac commodo.



                            Best Regards,
                            Sean.

                            Information Technology Department,
                            Senior Front End Designer</p>
                        {% endif %}
                    </div>
                    <div class="flotant-b-rigth">Ultima modificación : {{ notify.modified }}</div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- end row -->
<!-- begin row -->

{% endblock %}

{% block style %}
    <style>
    .btn-name-mdl-create{
        font-size: 14px;
    }
    .chip-user{
        width: 100%;
        text-align: center;
    }
    .bold{
        font-weight: bold !important;
        color:#0d3349;
    }
    .bbadge{
        float:left;
        width: 60px;
        text-align: center;
        margin-right:4px;
        border-radius:4px;
        font-size:10px;
        padding:2px 5px;
        color:#fff;
    }
    </style>
{% endblock %}

{% block script %}
<script>
    $(document).ready(function (){
        const csrfmiddlewaretoken = '{{ csrf_token }}';
        $('#btn-notify--important').click(function (){
            id = $(this).attr('data-id');
            $.post("{% url 'notify:post_change_important' %}",{csrfmiddlewaretoken, 'id':id}).done(function(data){
                if(data.error){
                    Swal.fire({
                      title: 'Upps !!',
                      text: data.msj,
                      icon: 'error',
                    }).then(function (){
                        location.reload();
                    });
                }else{
                    Swal.fire({
                      title: 'Genial !!',
                      text: data.msj,
                      icon: 'success',
                    }).then(function (){
                        location.reload();
                    });
                }
            })
        });
        $('#btn-notify--trash').click(function (){
            id = $(this).attr('data-id');
            $.post("{% url 'notify:post_change_trash' %}",{csrfmiddlewaretoken, 'id':id}).done(function(data){
                if(data.error){
                    Swal.fire({
                      title: 'Upps !!',
                      text: data.msj,
                      icon: 'error',
                    }).then(function (){
                        location.reload();
                    });
                }else{
                    Swal.fire({
                      title: 'Genial !!',
                      text: data.msj,
                      icon: 'success',
                    }).then(function (){
                        location.reload();
                    });
                }
            })
        });
        $('#btn-notify--response').click(function (){
            id = $(this).attr('data-id');
            Swal.fire({
              title: "Respuesta de Notificaciones",
              text: "Este funcionamiento por el momento no esta disponible en esta versión",
              icon: "info"
            });
        });
        $('#btn-notify--archivar').click(function (){
            Swal.fire({
                title: "Quiere archivar notificación?",
                text: "Una vez hecho esto desaparce de sus vistas",
                icon: "warning",
                showCancelButton: true,
                confirmButtonColor: "#3085d6",
                cancelButtonColor: "#d33",
                confirmButtonText: "Si, Archivar",
                cancelButtonText: "Cancelar"
            }).then((result) => {
              if (result.isConfirmed) {
                  id = $(this).attr('data-id');
                  $.post("{% url 'notify:post_change_active' %}",{csrfmiddlewaretoken, 'id':id}).done(function(data){
                    if(data.error){
                        Swal.fire({
                          title: 'Upps !!',
                          text: data.msj,
                          icon: 'error',
                        }).then(function (){
                            location.reload();
                        });
                    }else{
                        Swal.fire({
                          title: 'Genial !!',
                          text: data.msj,
                          icon: 'success',
                        }).then(function (){
                            location.reload();
                        });
                    }
                });
              }
            });
        });
    })

</script>

{% endblock%}