admin_apps/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('the_applications.users.urls', 'login'), namespace='login')),
    path('users/', include(('the_applications.users.urls', 'users'), namespace='users')),
    path('settings/', include(('the_applications.general_settings.urls', 'general_settings'), namespace='settings')),
    path('apps/', include(('the_applications.applications.urls', 'apps'), namespace='apps')),
    path('notify/', include(('the_applications.notify.urls', 'notify'), namespace='notify')),
    path('data/', include(('the_applications.datasheet.urls', 'data'), namespace='data')),
    path('rules/', include(('the_applications.rules.urls', 'rules'), namespace='rules')),
    path('typetransport/', include(('the_applications.type_transport.urls', 'typetransport'), namespace='typetransport')),
    path('zones/', include(('the_applications.zones.urls', 'zones'), namespace='zones')),
    path('api/', include(('the_applications.api.urls', 'api'), namespace='api')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

the_applications/rules/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path(
        route='',
        view=views.Principal.as_view(),
        name=''
    ),
    path(
        route='model',
        view=views.Modelx.as_view(),
        name='model'
    ),
    path(
        route='model2',
        view=views.Modelx2.as_view(),
        name='model2'
    ),
    path(
        route='create',
        view=views.UpdateModel.as_view(),
        name='create'
    ),
    path(
        route='update_model',
        view=views.UpdateModel.as_view(),
        name='update_model'
    ),
    path(
        route='datatables_model',
        view=views.DatatablesModel.as_view(),
        name='datatables_model'
    ),
    path(
        route='delete_rules',
        view=views.DatatablesDeleteRules.as_view(),
        name='delete_rules'
    ),
    path(
        route='active_toggle_rules',
        view=views.DatatablesActiveToggleRules.as_view(),
        name='active_toggle_rules'
    ),
    path(
        route='showid',
        view=views.ShowId,
        name='showid'
    ),
    path(
        route='get_filedsmodel_id',
        view=views.PostGetFieldsModelId.as_view(),
        name='get_filedsmodel_id'
    )
]

the_applications/rules/models.py
from django.contrib.auth.models import User
from django.db import models


class Model(models.Model):
    TYPE = [
        ("internal", "Interno"),
        ("external", "Postgresql"),
        ("file", "CSV"),
        ("api", "API"),
    ]
    STATUS = [
        ("ready", "Listo"),
        ("used", "En uso"),
    ]
    name = models.CharField(max_length=100, default='')
    description = models.TextField()
    type = models.CharField(max_length=20, choices=TYPE, default="internal")
    status = models.CharField(max_length=20, choices=STATUS, default="ready")
    tinternal_code = models.CharField(max_length=100, default='')
    tinternal_model = models.CharField(max_length=100, default='')
    tinternal_fields = models.TextField()
    texternal_host = models.CharField(max_length=100, default='')
    texternal_user = models.CharField(max_length=100, default='')
    texternal_password = models.CharField(max_length=100, default='')
    texternal_port = models.CharField(max_length=100, default='')
    texternal_db = models.CharField(max_length=100, default='')
    texternal_query = models.TextField()
    texternal_code = models.CharField(max_length=100, default='')
    texternal_model = models.CharField(max_length=100, default='')
    texternal_fields = models.TextField()
    tfile_code = models.CharField(max_length=100, default='')
    tfile_fields = models.TextField()
    tfile_path = models.TextField()
    tfile_binary = models.FileField(upload_to='file', max_length = 500)
    tapi_code = models.CharField(max_length=100, default='')
    tapi_fields = models.TextField()
    tapi_structure = models.TextField(default='')
    tapi_endpoint = models.TextField()
    active = models.SmallIntegerField(default=1)
    delete = models.SmallIntegerField(default=0)
    write_date = models.DateTimeField(auto_now_add=True)
    create_date = models.DateTimeField(auto_now_add=True)
    create_uid = models.IntegerField()
    write_uid = models.IntegerField()

class Header(models.Model):
    TYPE=[
        ("current","Actual"),
        ("model","Modelo"),
        ("models","Modelos"),
        ("semilla","Semilla"),
    ]
    ACTION = [
        ("equal", "Igual a"),
        ("greaterthan", "Mayor que"),
        ("lessthan", "Menor que"),
        ("contain", "Contiene"),
        ("notcontain", "No contiene"),
        ("lefteq", "Empieza con"),
        ("rigtheq", "Termina con"),
        ("notdefined", "No definido"),
        ("defined", "Definido"),
    ]
    RULE_EVAL = [
        ("value", "Valor"),
        ("values", "Valores"),
        ("field", "Campo"),
        ("fields", "Campos"),
        ("model", "Modelo"),
    ]
    EVAL = [
        ("omit", "Omitir"),
        ("perm", "Permancer"),
        ("group", "Agrupar"),
        ("categ", "Categorizar"),
        ("seed", "Semilla"),
    ]
    name = models.CharField(max_length=100, default='')
    code = models.CharField(max_length=50, default='')
    description = models.TextField()
    type = models.CharField(max_length=20, choices=TYPE, default="current")
    tcurrent_id = models.IntegerField()
    tcurrent_code = models.CharField(max_length=100, default='')
    tcurrent_fields = models.TextField()
    tmodel_id = models.IntegerField()
    tmodel_code = models.CharField(max_length=100, default='')
    tmodel_field = models.CharField(max_length=100, default='')
    tmodel_fields = models.TextField()
    tmodels_id = models.TextField()
    tmodels_code = models.TextField()
    tmodels_fields = models.TextField()
    tseed_id = models.IntegerField()
    tseed_code = models.TextField()
    action = models.CharField(max_length=20, choices=ACTION, default="equal")
    eval = models.CharField(max_length=20, choices=RULE_EVAL, default="value")
    avalue = models.CharField(max_length=500, default='')
    avaluescomp = models.TextField(default="")
    avalues = models.TextField()
    afield = models.CharField(max_length=200, default='')
    afieldscomp = models.TextField(default="")
    afields = models.TextField()
    amodel_id = models.IntegerField()
    amodel_code = models.CharField(max_length=100, default='')
    amodel_field = models.CharField(max_length=100, default='')
    amodel_fields = models.TextField()
    amodel_fieldscomp = models.TextField(default="")
    active = models.SmallIntegerField(default=1)
    write_date = models.DateTimeField(auto_now_add=True)
    create_date = models.DateTimeField(auto_now_add=True)
    create_uid = models.IntegerField()
    write_uid = models.IntegerField()

the_applications/rules/views.py
#django
from django.views.generic import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin
from the_applications.rules.forms import ModelsRule as MR, ModelsRuleUpdate as MR2, HeaderRule as HM
from the_applications.datasheet.models import ModelReg as MoReg, Header as Cond
from the_applications.rules.models import Model as M
from django.apps import apps
from django.contrib.auth.decorators import login_required
import psycopg2
import requests
import the_applications.func as f
from django.contrib.auth.models import User
from the_applications.notify.models import TypeNotify, Notify
from django.shortcuts import render, redirect

from the_applications.notify.forms import NotifyForm
from django.http import HttpResponse, JsonResponse
from django.db.models import Count
import json
import the_applications.func as f
from datetime import datetime, timezone
import timeago
# Model

class Principal(LoginRequiredMixin, TemplateView):
    template_name = 'rules/main.html'

    def get_context_data(self, **kwargs):
        context2 = super().get_context_data(**kwargs)
        fmodel = MR()
        fheader = HM()
        context2["models"] = fmodel
        context2["header"] = fheader
        return context2


class Modelx2(LoginRequiredMixin, TemplateView):
    template_name = 'rules/main.html'

    def post(self, request, *args, **kwargs):
        context2 = {
            'erros': []
        }
        response = {
            'data': [],
            'error': False,
            'msj': ''
        }
        data = request.POST
        file = request.FILES
        print("---------------------------------->")
        print(data)
        print(file)
        print("---------------------------------->")


class Modelx(LoginRequiredMixin, TemplateView):
    template_name = 'rules/main.html'

    def post(self, request, *args, **kwargs):
        context2 = {
            'erros': []
        }
        response = {
            'data': [],
            'error': False,
            'msj': ''
        }
        data = request.POST
        file = request.FILES
        form = MR(data,file)
        if form.is_valid():
            type = data["type"]
            print("********************** [START EVAL]")
            print(type)
            if type == "internal":
                fields = data["tinternal_fields"]
                tinternal_code = data["tinternal_code"]
                tinternal_model = data["tinternal_model"]
                if not len(tinternal_code) > 0 :
                    response["msj"] = """{} ▪ No existe el nombre de la tabla.""".format(response["msj"])
                    response["error"] = True
                if not len(tinternal_model) > 0 :
                    response["msj"] = """{} ▪ No existe el nombre del modelo django.""".format(response["msj"])
                    response["error"] = True
                if not len(fields) > 0 :
                    response["msj"] = """{} ▪ No existen campos del modelo.""".format(response["msj"])
                    response["error"] = True
                if response["error"]:
                    response["msj"] = """{} ▪ "Los datos son necesarios". """.format(response["msj"])
                else:
                    response["msj"] = "Se ha guardado el modelo y ya puede ser utilizado en las condiciones."
                    if tinternal_code == "current":
                        tinternal_code = 'datasheet_datasheet'
                    model = next((m for m in apps.get_models() if m._meta.db_table==tinternal_code), None)
                    if model:
                        model2 = MoReg.objects.filter(name=tinternal_model).all()
                        if model2:
                            print("**************************")
                            print("---> ", model2)
                            form.save(user=request.user.id)
                            type_notify = TypeNotify.objects.get(pk=1)
                            new_notify = Notify(
                                user=request.user,
                                type=type_notify,
                                name="Nuevo modelo Interno - {}".format(str(tinternal_model)),
                                description="""
                                                   El usuario "{} {}"  ha generado un nuevo modelo de tipo "INTERNO" con
                                                    el identificador "{}". Este tipo de modelos interactuan directamente
                                                    con la base de Datos de Roadly, Ocupando cualquier catalogo interno
                                                    como herramienta de evalución.
                                                    
                                                    
                                                   """.format(request.user.first_name, request.user.last_name,
                                                              str(tinternal_model)),
                                priority=1,
                                picture='notify/pictures/model.png'
                            )
                            new_notify.save()
                        else:
                            response["msj"] = """No coincide el nombre de modelo de DJango con alguno existente en Roadly"""
                            response["error"] = True
                    else:
                        response["msj"] = """No coincide el nombre de la tabla con algun existente en Roadly"""
                        response["error"] = True
                    print("***********************")
            elif type == "external":
                print("*********************** [External Start]")
                texternal_host = data["texternal_host"]
                texternal_user = data["texternal_user"]
                texternal_password = data["texternal_password"]
                texternal_port = data["texternal_port"]
                texternal_db = data["texternal_db"]
                texternal_query = data["texternal_query"]
                texternal_code = data["texternal_code"]
                texternal_model = data["texternal_model"]
                texternal_fields = data["texternal_fields"]
                if not len(texternal_host) > 0 :
                    response["msj"] = """{} ▪ No existe el Host de conexión a DB.""".format(response["msj"])
                    response["error"] = True
                if not len(texternal_user) > 0 :
                    response["msj"] = """{} ▪ No existe el Usuario de conexión a DB.""".format(response["msj"])
                    response["error"] = True
                if not len(texternal_password) > 0 :
                    response["msj"] = """{} ▪ No existe la Contraseña de conexión a DB.""".format(response["msj"])
                    response["error"] = True
                if not len(texternal_port) > 0 :
                    response["msj"] = """{} ▪ No existe el Puerto de conexión a DB.""".format(response["msj"])
                    response["error"] = True
                if not len(texternal_db) > 0 :
                    response["msj"] = """{} ▪ No existe el Nombre de la DB.""".format(response["msj"])
                    response["error"] = True
                if not len(texternal_query) > 0 :
                    response["msj"] = """{} ▪ No existe Query para la extracción de información.""".format(response["msj"])
                    response["error"] = True
                if not len(texternal_code) > 0 :
                    response["msj"] = """{} ▪ No existe el Nombre técnico de la extracción.""".format(response["msj"])
                    response["error"] = True
                if not len(texternal_model) > 0 :
                    response["msj"] = """{} ▪ No existe el Nombre de la Tablas o Vista.""".format(response["msj"])
                    response["error"] = True
                if not len(texternal_fields) > 0 :
                    response["msj"] = """{} ▪ No hay campos que extraer. Es importante colocar los campos a utilizar.""".format(response["msj"])
                    response["error"] = True
                if response["error"]:
                    response["msj"] = """{} ▪ "Los datos son necesarios". """.format(response["msj"])
                else:
                    params = {
                        "host": texternal_host,
                        "port": texternal_port,
                        "user": texternal_user,
                        "password": texternal_password,
                        "database": texternal_db
                    }
                    conn = psycopg2.connect(**params)
                    if conn:
                        cur = conn.cursor()
                        cur.execute(texternal_query)
                        xquery = cur.fetchall()
                        if len(xquery) > 0:
                            print("************************** [Se guarda modelo - START] ")
                            response["error"] = False
                            response["msj"] = "Se ha guardado el modelo y ya puede ser utilizado en las condiciones."
                            form.save(user=request.user.id)
                            type_notify = TypeNotify.objects.get(pk=1)
                            new_notify = Notify(
                                user=request.user,
                                type=type_notify,
                                name="Nuevo modelo Postgresql - {}".format(str(texternal_model)),
                                description="""
                                           El usuario "{} {}"  ha generado un nuevo modelo de tipo "EXTERNO" con
                                            el identificador "{}". Este tipo de modelos generan una relación ODBC           
                                            con alguna base de datos generada Postgresql. Dentro de los parámetros

templates/rules/show.html
{% extends 'base.html' %}
{% load static %}

{% block sitio %}
    <li class="breadcrumb-item"><a href="{% url 'rules:' %}">Condiciones</a></li>
    <li class="breadcrumb-item"><a href="{% url 'rules:' %}">Modelo</a></li>
{% endblock %}


{% block content %}
{% csrf_token %}
<!-- begin row -->
<h3>Modelo({{ name }})</h3><br>
<div class="row">
    <div class="col-md-12">
        <div class="panel panel-inverse">
            <div class="panel-heading">
                <h4 class="panel-title">.</h4>
                <div class="panel-heading-btn">
                    <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-default" data-click="panel-expand"><i class="fa fa-expand"></i></a>
                    <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-success" data-click="panel-reload"><i class="fa fa-redo"></i></a>
                    <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-warning" data-click="panel-collapse"><i class="fa fa-minus"></i></a>
                    <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-danger" data-click="panel-remove"><i class="fa fa-times"></i></a>
                </div>
            </div>
            <div class="panel-body m-20">
                 <div class="row">
                     <div class="col-12 m-b-30" >
                         <div class="card" style="padding: 30px;border: none !important;">
                             <div class="cpage-card" style="display: block;">
                                <div class="lphead">
                                    <a class="rew-btn" href="{% url 'rules:' %}" ><iconify-icon style="font-size: 14px;" icon="solar:multiple-forward-left-bold-duotone"></iconify-icon>Volver</a>
                                </div>
                                 <div class="lpbody">
                                    <style>
                                         .helptext{top: 5px !important;}
                                    </style>
                                    <form id="act-model" action="{% url 'rules:update_model' %}" method="post">
                                        {% csrf_token %}
                                        <!--<input type="text" name="id" id="id" value="{{ id }}" hidden/>-->
                                        {% load form_extras %}
                                        {% for field in models %}
                                             <div class="form-group row {{ field|get_class }}">
                                                <div for="{{ field.label }}" class="col-sm-12 col-form-label">
                                                    {{ field.label_tag }}
                                                </div>
                                                <div class="col-sm-12">
                                                    {{ field }}
                                                    {% if field.help_text %}
                                                        <small class="helptext">{{ field.help_text }}</small>
                                                    {% endif %}
                                                </div>
                                            </div>
                                        {% endfor %}
                                        <br>
                                        <input class="btn btn-success" type="submit" value="Actualizar">
                                     </form>
                                 </div>
                             </div>
                         </div>
                     </div>

                </div>
            </div>
        </div>
    </div>
</div>
<!-- end row -->
<!-- begin row -->

{% endblock %}

{% block style %}
    <style>
    .rc-id{
        display:none;
    }
    .btn-name-mdl-create{
        font-size: 14px;
    }
    .chip-user{
        width: 100%;
        text-align: center;
    }
    .bold{
        font-weight: bold !important;
        color:#0d3349;
    }
    .badge{
        background: transparent !important;
    }
    .state-li{
        color: #000000;
        border: 1px solid #00000038;
        background: #c6c6c6;
        display: inline-block;
        min-width: 100px;
        max-width: 100px;
        padding: 4px 10px;
        text-align: center;
        border-radius: 5px;
    }
    .state-as{
        color: #ffffff;
        border: 1px solid #00000038;
        background: #009688;
        display: inline-block;
        min-width: 100px;
        max-width: 100px;
        padding: 4px 10px;
        text-align: center;
        border-radius: 5px;
    }
    .state-an{
        color: #ffffff;
        border: 1px solid #00000038;
        background: #03A9F4;
        display: inline-block;
        min-width: 100px;
        max-width: 100px;
        padding: 4px 10px;
        text-align: center;
        border-radius: 5px;
    }
    .state-cl{
        color: #000000;
        border: 1px solid #00000038;
        background: #ffb64c;
        display: inline-block;
        min-width: 100px;
        max-width: 100px;
        padding: 4px 10px;
        text-align: center;
        border-radius: 5px;
    }
    .state-ap{
        color: #ffffff;
        border: 1px solid #00000038;
        background: #4CAF50;
        display: inline-block;
        min-width: 100px;
        max-width: 100px;
        padding: 4px 10px;
        text-align: center;
        border-radius: 5px;
    }
    .state-o-cp{
        color: #ffffff;
        border: 1px solid #00000038;
        background: #8859db;
        display: inline-block;
        min-width: 100px;
        max-width: 100px;
        padding: 4px 10px;
        text-align: center;
        border-radius: 5px;
    }
    .state-o-ca{
        color: #ffffff;
        border: 1px solid #00000038;
        background: #22c4b5;
        display: inline-block;
        min-width: 100px;
        max-width: 100px;
        padding: 4px 10px;
        text-align: center;
        border-radius: 5px;
    }
    .state-f-fs{
        color: #ffffff;
        border: 1px solid #00000038;
        background: #e44949;
        display: inline-block;
        min-width: 100px;
        max-width: 100px;
        padding: 4px 10px;
        text-align: center;
        border-radius: 5px;
    }
    table.dataTable.cell-border>tbody>tr>* {
        border-right: none !important;
    }
    table.dataTable.cell-border>tbody>tr>*:first-child {
        border-left: none !important;
    }
    table.dataTable.display tbody tr:hover.selected > .sorting_1, table.dataTable.order-column.hover tbody tr:hover.selected > .sorting_1 {
        box-shadow: inset 0 0 0 9999px rgb(255, 245, 220) !important;
    }
    table.dataTable.stripe > tbody > tr:nth-child(odd).selected > *, table.dataTable.display > tbody > tr:nth-child(odd).selected > * {
        box-shadow: inset 0 0 0 9999px rgb(255, 245, 220) !important;
    }
    table.dataTable.display > tbody > tr.selected + tr.selected > td {
        box-shadow: inset 0 0 0 9999px rgb(255, 245, 220) !important;
    }
    table.dataTable.display > tbody > tr.selected:hover > * {
        box-shadow: inset 0 0 0 9999px rgb(255, 245, 220) !important;
    }
    table.dataTable.display > tbody tr.selected > .sorting_1{
        box-shadow: inset 0 0 0 9999px rgb(255, 245, 220) !important;
    }
    table.dataTable.hover > tbody > tr.selected:hover > *, table.dataTable.display > tbody > tr.selected:hover > * {
      box-shadow: inset 0 0 0 9999px rgb(255, 245, 220) !important;
    }
    table.dataTable.stripe > tbody > tr:nth-child(odd).selected > *, table.dataTable.display > tbody > tr:nth-child(odd).selected > * {
      box-shadow: inset 0 0 0 9999px rgb(255, 245, 220) !important;
    }
    .rc-endpoint, .rc-file, .rc-external, .rc-internal {
        display: none;
    }
    .add-fields--internal input, .add-fields--external input, .add-fields--file input{
        height: 35.3px;
    }
    </style>
{% endblock %}

{% block script %}
<script>
    $(document).ready(function (){
        type = '{{ type }}';
        switch (type) {
            case 'internal':
                $(".rc-internal").css('display','block');
                $("#id_tinternal_fields").attr('readonly',false);
                break;
            case 'external':
                $(".rc-external").css('display','block');
                break;
            case 'file':
                $(".rc-file").css('display','block');
                break;
            case 'api':
                $(".rc-endpoint").css('display','block');
                break;
        }

    });

</script>
{% endblock%}
