admin_apps/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('the_applications.users.urls', 'login'), namespace='login')),
    path('users/', include(('the_applications.users.urls', 'users'), namespace='users')),
    path('settings/', include(('the_applications.general_settings.urls', 'general_settings'), namespace='settings')),
    path('apps/', include(('the_applications.applications.urls', 'apps'), namespace='apps')),
    path('notify/', include(('the_applications.notify.urls', 'notify'), namespace='notify')),
    path('data/', include(('the_applications.datasheet.urls', 'data'), namespace='data')),
    path('rules/', include(('the_applications.rules.urls', 'rules'), namespace='rules')),
    path('typetransport/', include(('the_applications.type_transport.urls', 'typetransport'), namespace='typetransport')),
    path('zones/', include(('the_applications.zones.urls', 'zones'), namespace='zones')),
    path('api/', include(('the_applications.api.urls', 'api'), namespace='api')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

the_applications/notify/urls.py
from django.urls import path
from . import views


urlpatterns = [

    path(
        route='panel',
        view=views.Principal.as_view(),
        name='panel'
    ),
    path(
        route='type',
        view=views.Type.as_view(),
        name='type'
    ),
    path(
        route='inbox',
        view=views.Inbox.as_view(),
        name='inbox'
    ),
    path(
        route='create_type',
        view=views.CreateTypeNotify.as_view(),
        name='create_type'
    ),
    path(
        route='create_notify',
        view=views.CreateNotify.as_view(),
        name='create_notify'
    ),
    path(
        route='datatables_type_notify',
        view=views.DatatablesTypeNotify.as_view(),
        name='datatables_type_notify'
    ),
    path(
        route='datatables_notify',
        view=views.DatatablesNotify.as_view(),
        name='datatables_notify'
    ),
    path(
        route='datatables_notify_inbox',
        view=views.DatatablesNotifyInbox.as_view(),
        name='datatables_notify_inbox'
    ),
    path(
        route='datatables_notify_important',
        view=views.DatatablesNotifyImportant.as_view(),
        name='datatables_notify_important'
    ),
    path(
        route='datatables_notify_trash',
        view=views.DatatablesNotifyTrash.as_view(),
        name='datatables_notify_trash'
    ),
    path(
        route='datatables_notify_send',
        view=views.DatatablesNotifySend.as_view(),
        name='datatables_notify_send'
    ),
    path(
        route='showid',
        view=views.ShowId,
        name='showid'
    ),
    path(
        route='labelshow',
        view=views.LabelShow,
        name='labelshow'
    ),
    path(
        route='post_change_important',
        view=views.PostChangeImportant.as_view(),
        name='post_change_important'
    ),
    path(
        route='post_change_trash',
        view=views.PostChangeTrash.as_view(),
        name='post_change_trash'
    ),
    path(
        route='post_change_active',
        view=views.PostChangeActive.as_view(),
        name='post_change_active'
    ),
    path(
        route='post_change_deactive',
        view=views.PostChangeDeactive.as_view(),
        name='post_change_deactive'
    ),
    path(
        route='post_change_active_type',
        view=views.PostChangeActiveType.as_view(),
        name='post_change_active_type'
    ),
    path(
        route='post_change_deactive_type',
        view=views.PostChangeDeactiveType.as_view(),
        name='post_change_deactive_type'
    ),
    path(
        route='inbox',
        view=views.GetNotifyInbox.as_view(),
        name='inbox'
    ),
    path(
        route='important',
        view=views.GetNotifyImportant.as_view(),
        name='important'
    ),
    path(
        route='send',
        view=views.GetNotifySend.as_view(),
        name='send'
    ),
    path(
        route='trash',
        view=views.GetNotifyTrash.as_view(),
        name='trash'
    ),
    path(
        route='one',
        view=views.PostChangeActive.as_view(),
        name='one'
    ),
    path(
        route='new',
        view=views.New.as_view(),
        name='new'
    ),

   

]

the_applications/users/urls.py
from django.urls import path
from . import views


urlpatterns = [

    path(
        route='',
        view=views.LoginView.as_view(redirect_authenticated_user=True),
        name='login'
    ),

    # path(
    #     route='logout/',
    #     view=views.LogoutView.as_view(),
    #     name='logout'
    # ),

    path(
        route='logout/',
        view=views.logout,
        name='logout'
    ),
    path(
        route='signup/',
        view=views.SignupView.as_view(),
        name='signup'
    ),

    path(
        route='me/profile',
        view=views.update_profile,
        name="update_profile"
    ),

]

the_applications/notify/forms.py
"""Apps forms."""
import os
# Django
from django import forms
from the_applications.notify.models import TypeNotify, Notify
from django.contrib.auth.models import User

class TypeNotifyForm(forms.Form):
    name = forms.CharField(max_length=50, required=True)
    color = forms.CharField(max_length=50, required=True)
    description = forms.CharField(max_length=400, required=False)

    def clean_name(self):
        if not self.cleaned_data['name']:
            raise forms.ValidationError('Es obligatorio poner un "nombre"')
        return self.cleaned_data['name']

    def clean_color(self):
        if not self.cleaned_data['color']:
            raise forms.ValidationError('Es obligatorio poner un "color"')
        return self.cleaned_data['color']

    def save(self):
        data = self.cleaned_data
        print("-------------------------------------------- [SAVE] ->")
        type = TypeNotify()
        type.name = data["name"]
        type.color = data["color"]
        type.description = data["description"]
        print(type)
        type.save()
        print("-------------------------------------------- [SAVE] <-")

class NotifyForm(forms.Form):

    user = forms.IntegerField(required=True)
    type = forms.IntegerField(required=True)
    name = forms.CharField(max_length=50, required=True)
    description = forms.CharField(max_length=400, required=True)
    priority = forms.IntegerField(required=True)
    picture = forms.CharField(max_length=400, required=False)

    def clean_user(self):
        if not self.cleaned_data['user']:
            raise forms.ValidationError('Es obligatorio seleccionar un "usuario" para la notificación')
        return self.cleaned_data['user']
    def clean_type(self):
        if not self.cleaned_data['type']:
            raise forms.ValidationError('Es obligatorio seleccionar un "tipo" de notificación')
        return self.cleaned_data['type']
    def clean_name(self):
        if not self.cleaned_data['name']:
            raise forms.ValidationError('Es obligatorio poner un "nombre"')
        return self.cleaned_data['name']

    def clean_description(self):
        if not self.cleaned_data['description']:
            raise forms.ValidationError('Es obligatorio poner una "descripción"')
        return self.cleaned_data['description']

    def clean_priority(self):
        if not self.cleaned_data['priority']:
            raise forms.ValidationError('Es obligatorio poner la "prioridad" de la notificación')
        return self.cleaned_data['priority']

    def save(self, data):
        print("-------------------------------------------- [SAVE] ->")
        print(data)
        notify = Notify()
        notify.name = data['name']
        notify.user = User.objects.get(id=data['user'])
        notify.type = TypeNotify.objects.get(id=data['type'])
        notify.to = data['from']
        notify.description = data['description']
        notify.priority = data['priority']
        if data['picture']:
            notify.picture = data['picture']
        notify.save()
        print("-------------------------------------------- [SAVE] <-")

templates/navbar.html
{% load static %}
<div id="header" class="header navbar-default navbar-expand">
    <!-- begin navbar-header -->
    <div class="navbar-header">
        <a href="{% url 'general_settings:ping' %}" class="navbar-brand"><img src="{% static 'img/datalist/gps.png' %}">
            <b><span id="name_app"></span> |</b> <div style="margin-left: 5px;"><span id="info_app"></span></div></a>
        <button type="button" class="navbar-toggle" data-click="sidebar-toggled">
            <span class="icon-bar"></span>
        </button>
    </div>
    <!-- end navbar-header --><!-- begin header-nav -->
    <ul class="navbar-nav navbar-right">
        <li class="navbar-form">
            <form action="" method="POST" name="search_form" id="search_form">
                <div class="form-group">
                    <input type="text" class="form-control" placeholder="Enter keyword"/>
                    <button type="submit" class="btn btn-search"><i class="fa fa-search"></i></button>
                </div>
            </form>
        </li>

      <!----------------------------------------->

        <li class="dropdown">
            <a href="#" data-toggle="dropdown" class="dropdown-toggle f-s-14" id="bell">
            </a>

            <div class="dropdown-menu media-list dropdown-menu-right">
                <div class="dropdown-header" id="bell-wants">NO TIENES NOTIFICACIONES</div>
                <div id="add_notify"></div>
                <div class="dropdown-footer text-center">
                    <a href="{% url 'notify:panel' %}">View more</a>
                </div>
            </div>
        </li>

        <!----------------------------------------->

        <li class="dropdown navbar-user">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <div class="image">
                    {% if request.user.profile.picture %}
                    <img src="{{ request.user.profile.picture.url }}" class="rounded-circle" width="50"
                         height="50"/>
                    {% else %}
                    <img src="{% static 'img/users/user.png' %}" class="rounded-circle" height="50"/>
                    {% endif %}
                </div>
                <span class="d-none d-md-inline"><span id="id_user"></span></span> <b class="caret"></b>
            </a>
            <div class="dropdown-menu dropdown-menu-right">
                <a href="{% url 'users:update_profile' %}" class="dropdown-item">Editar Perfil</a>
                <a href="{% url 'notify:inbox' %}" class="dropdown-item"><span class="badge badge-danger pull-right badgeinbox2"></span> Inbox</a>
                <a href="javascript:;" class="dropdown-item" style="text-decoration: none;font-weight: normal">Calendar</a>
                <a href="javascript:;" class="dropdown-item" style="text-decoration: none;font-weight: normal">Setting</a>
                <div class="dropdown-divider"></div>
                <a href="{% url 'users:logout' %}" class="dropdown-item">Log Out</a>
            </div>
        </li>
    </ul>
    <!-- end header navigation right -->
</div>

templates/sidebar.html
{% load static %}


<!-- begin #sidebar -->
<div id="sidebar" class="sidebar">
    <!-- begin sidebar scrollbar -->
    <div data-scrollbar="true" data-height="100%" style="background: linear-gradient(21deg, rgb(203 217 225) 0%, rgb(238 248 254) 35%, rgb(255 255 255) 100%);">
        <!-- begin sidebar user -->
        <ul class="nav">
            <li class="nav-profile">
                <a href="javascript:;" data-toggle="nav-profile" style="height: 200px;">
                    <div class="cover with-shadow"></div>
                    <div class="down"><iconify-icon icon="solar:round-arrow-down-bold-duotone"></iconify-icon></div>
                </a>
            </li>
            <li>
                <ul class="nav nav-profile">
                    <li><a href="{% url 'users:update_profile' %}"><i class="fa fa-cog"></i>Editar Perfil</a></li>
                    <li><a href="javascript:;"><i class="fa fa-question-circle"></i> Ayuda</a></li>

                </ul>
            </li>
        </ul>
        <!-- end sidebar user -->
    
    <!-- begin sidebar nav -->
    <ul class="nav">
        <li class="nav-header">Navigation</li>
        <!-- Panel Delvelop = Use active in class has-sub -->
        <li class="has-sub">
            <a href="javascript:;">
                <a href="{% url 'general_settings:ping' %}">
                    <iconify-icon class="solar-navbar" icon="solar:widget-bold-duotone"></iconify-icon>
                    <span>My Panel</span>
                </a>
            </a>
        </li>
        <!-- End Panel Delvelop -->

        <li class="has-sub">
            <a href="javascript:;">
                <b class="caret"></b>
                <iconify-icon class="solar-navbar" icon="solar:mailbox-bold-duotone"></iconify-icon>
                <span>Notificaciones</span>
            </a>
            <ul class="sub-menu">
                <li>
                    <a href="{% url 'notify:panel' %}">
                        <i class="fas fa-key fa-sm"></i>
                        Notificaciones Globales
                    </a>
                </li>
                <li>
                    <a href="{% url 'notify:type' %}">
                        <i class="fas fa-key fa-sm"></i>
                        Tipo Notificación
                    </a>
                </li>
                <li><a href="{% url 'notify:inbox' %}">Inbox</a></li>
                <li><a href="{% url 'notify:important' %}">Importante</a></li>
                <li><a href="{% url 'notify:send' %}">Enviado</a></li>
                <li><a href="{% url 'notify:trash' %}">Basura</a></li>
            </ul>
        </li>
        <li class="has-sub ">
            <a href="{% url 'data:' %}">
                <iconify-icon class="solar-navbar" icon="solar:bill-list-bold-duotone"></iconify-icon>
                <span>Data List</span>
            </a>
        </li>
        <li class="has-sub ">
            <a href="{% url 'rules:' %}">
                <iconify-icon class="solar-navbar" icon="solar:ruler-cross-pen-bold-duotone"></iconify-icon>
                <span>Condiciones</span>
            </a>
        </li>
        <li class="has-sub ">
            <a href="{% url 'typetransport:' %}">
                <iconify-icon class="solar-navbar" icon="solar:bus-bold-duotone"></iconify-icon>
                <span>Tipo de transporte</span>
            </a>
        </li>
        <li class="has-sub ">
            <a href="{% url 'zones:' %}">
                <iconify-icon class="solar-navbar" icon="solar:globus-bold-duotone"></iconify-icon>
                <span>Zonas</span>
            </a>
        </li>
        <li class="has-sub ">
            <a href="#">
                <iconify-icon class="solar-navbar" icon="solar:box-minimalistic-bold-duotone"></iconify-icon>
                <span>New App</span>
            </a>
        </li>

        <style>
            .sidebar-minify-btn:hover, .sidebar-minify-btn:after, .sidebar-minify-btn:active{
                background: red !important;
            }
        </style>
        <!-- begin sidebar minify button -->
        <li class="smin" data-t="0">
            <a href="javascript:;" data-click="sidebar-minify" style="padding: 0px !important;">
                <iconify-icon class="solar-navbar green" style="margin:0px !important;" icon="solar:round-arrow-left-bold-duotone"></iconify-icon>
            </a>
        </li>
        <!-- end sidebar minify button -->
    </ul>
    <!-- end sidebar nav -->
</div>
<!-- end sidebar scrollbar -->
</div>
<div class="sidebar-bg"></div>
<!-- end #sidebar -->

templates/theme_panel.html
{% load static %}
<!-- BEGIN THEME PANEL -->
		<div class="theme-panel theme-panel-lg">
			<a href="javascript:;" data-click="theme-panel-expand" class="theme-collapse-btn"><i class="fa fa-cog"></i></a>
			<div class="theme-panel-content">
				<h5>Paletas de color</h5>

                {% if request.user.profile.theme == 'material' %}
                    <link href="{% static 'assets/css/material/app.min.css' %}" rel="stylesheet" />
                 {% elif request.user.profile.theme == 'apple' %}
                    <ul class="theme-list clearfix">
                        <li><a href="javascript:;" class="bg-red" data-theme="red" data-theme-file="{% static 'assets/css/apple/theme/red.min.css' %}" data-click="theme-selector" data-toggle="tooltip" data-trigger="hover" data-container="body" data-title="Red">&nbsp;</a></li>
                        <li><a href="javascript:;" class="bg-pink" data-theme="pink" data-theme-file="{% static 'assets/css/apple/theme/pink.min.css' %}" data-click="theme-selector" data-toggle="tooltip" data-trigger="hover" data-container="body" data-title="Pink">&nbsp;</a></li>
                        <li><a href="javascript:;" class="bg-orange" data-theme="orange" data-theme-file="{% static 'assets/css/apple/theme/orange.min.css' %}" data-click="theme-selector" data-toggle="tooltip" data-trigger="hover" data-container="body" data-title="Orange">&nbsp;</a></li>
                        <li><a href="javascript:;" class="bg-yellow" data-theme="yellow" data-theme-file="{% static 'assets/css/apple/theme/yellow.min.css' %}" data-click="theme-selector" data-toggle="tooltip" data-trigger="hover" data-container="body" data-title="Yellow">&nbsp;</a></li>
                        <li><a href="javascript:;" class="bg-lime" data-theme="lime" data-theme-file="{% static 'assets/css/apple/theme/lime.min.css' %}" data-click="theme-selector" data-toggle="tooltip" data-trigger="hover" data-container="body" data-title="Lime">&nbsp;</a></li>
                        <li><a href="javascript:;" class="bg-green" data-theme="green" data-theme-file="{% static 'assets/css/apple/theme/green.min.css' %}" data-click="theme-selector" data-toggle="tooltip" data-trigger="hover" data-container="body" data-title="Green">&nbsp;</a></li>
                        <li class="active"><a href="javascript:;" class="bg-teal" data-theme="default" data-theme-file="" data-click="theme-selector" data-toggle="tooltip" data-trigger="hover" data-container="body" data-title="Default">&nbsp;</a></li>
                        <li><a href="javascript:;" class="bg-aqua" data-theme="aqua" data-theme-file="{% static 'assets/css/apple/theme/aqua.min.css' %}" data-click="theme-selector" data-toggle="tooltip" data-trigger="hover" data-container="body" data-title="Aqua">&nbsp;</a></li>
                        <li><a href="javascript:;" class="bg-blue" data-theme="blue" data-theme-file="{% static 'assets/css/apple/theme/blue.min.css' %}" data-click="theme-selector" data-toggle="tooltip" data-trigger="hover" data-container="body" data-title="Blue">&nbsp;</a></li>
                        <li><a href="javascript:;" class="bg-purple" data-theme="purple" data-theme-file="{% static 'assets/css/apple/theme/purple.min.css' %}" data-click="theme-selector" data-toggle="tooltip" data-trigger="hover" data-container="body" data-title="Purple">&nbsp;</a></li>
                        <li><a href="javascript:;" class="bg-indigo" data-theme="indigo" data-theme-file="{% static 'assets/css/apple/theme/indigo.min.css' %}" data-click="theme-selector" data-toggle="tooltip" data-trigger="hover" data-container="body" data-title="Indigo">&nbsp;</a></li>
                        <li><a href="javascript:;" class="bg-black" data-theme="black" data-theme-file="{% static 'assets/css/apple/theme/black.min.css' %}" data-click="theme-selector" data-toggle="tooltip" data-trigger="hover" data-container="body" data-title="Black">&nbsp;</a></li>
				    </ul>
   
                 {% elif request.user.profile.theme == 'transparent' %}
                     <ul class="theme-list clearfix">
                        <li><a href="javascript:;" class="bg-red" data-theme="red" data-theme-file="{% static 'assets/css/transparent/theme/red.min.css' %}" data-click="theme-selector" data-toggle="tooltip" data-trigger="hover" data-container="body" data-title="Red">&nbsp;</a></li>
                        <li><a href="javascript:;" class="bg-pink" data-theme="pink" data-theme-file="{% static 'assets/css/transparent/theme/pink.min.css' %}" data-click="theme-selector" data-toggle="tooltip" data-trigger="hover" data-container="body" data-title="Pink">&nbsp;</a></li>
                        <li><a href="javascript:;" class="bg-orange" data-theme="orange" data-theme-file="{% static 'assets/css/transparent/theme/orange.min.css' %}" data-click="theme-selector" data-toggle="tooltip" data-trigger="hover" data-container="body" data-title="Orange">&nbsp;</a></li>
                        <li><a href="javascript:;" class="bg-yellow" data-theme="yellow" data-theme-file="{% static 'assets/css/transparent/theme/yellow.min.css' %}" data-click="theme-selector" data-toggle="tooltip" data-trigger="hover" data-container="body" data-title="Yellow">&nbsp;</a></li>
                        <li><a href="javascript:;" class="bg-lime" data-theme="lime" data-theme-file="{% static 'assets/css/transparent/theme/lime.min.css' %}" data-click="theme-selector" data-toggle="tooltip" data-trigger="hover" data-container="body" data-title="Lime">&nbsp;</a></li>
                        <li><a href="javascript:;" class="bg-green" data-theme="green" data-theme-file="{% static 'assets/css/facebook/theme/green.min.css' %}" data-click="theme-selector" data-toggle="tooltip" data-trigger="hover" data-container="body" data-title="Green">&nbsp;</a></li>
                        <li class="active"><a href="javascript:;" class="bg-teal" data-theme="default" data-theme-file="" data-click="theme-selector" data-toggle="tooltip" data-trigger="hover" data-container="body" data-title="Default">&nbsp;</a></li>
                        <li><a href="javascript:;" class="bg-aqua" data-theme="aqua" data-theme-file="{% static 'assets/css/transparent/theme/aqua.min.css' %}" data-click="theme-selector" data-toggle="tooltip" data-trigger="hover" data-container="body" data-title="Aqua">&nbsp;</a></li>
                        <li><a href="javascript:;" class="bg-blue" data-theme="blue" data-theme-file="{% static 'assets/css/transparent/theme/blue.min.css' %}" data-click="theme-selector" data-toggle="tooltip" data-trigger="hover" data-container="body" data-title="Blue">&nbsp;</a></li>
                        <li><a href="javascript:;" class="bg-purple" data-theme="purple" data-theme-file="{% static 'assets/css/transparent/theme/purple.min.css' %}" data-click="theme-selector" data-toggle="tooltip" data-trigger="hover" data-container="body" data-title="Purple">&nbsp;</a></li>
                        <li><a href="javascript:;" class="bg-indigo" data-theme="indigo" data-theme-file="{% static 'assets/css/transparent/theme/indigo.min.css' %}" data-click="theme-selector" data-toggle="tooltip" data-trigger="hover" data-container="body" data-title="Indigo">&nbsp;</a></li>
                        <li><a href="javascript:;" class="bg-black" data-theme="black" data-theme-file="{% static 'assets/css/transparent/theme/black.min.css' %}" data-click="theme-selector" data-toggle="tooltip" data-trigger="hover" data-container="body" data-title="Black">&nbsp;</a></li>
				    </ul>
                {% endif %}


				<div class="divider"></div>
				<div class="row m-t-10">
					<div class="col-6 control-label text-inverse f-w-600">Header Fixed</div>
					<div class="col-6 d-flex">
						<div class="custom-control custom-switch ml-auto">
							<input type="checkbox" class="custom-control-input" name="header-fixed" id="headerFixed" value="1" checked />
							<label class="custom-control-label" for="headerFixed">&nbsp;</label>
						</div>
					</div>
				</div>
				<div class="row m-t-10">
					<div class="col-6 control-label text-inverse f-w-600">Header Inverse</div>
					<div class="col-6 d-flex">
						<div class="custom-control custom-switch ml-auto">
							<input type="checkbox" class="custom-control-input" name="header-inverse" id="headerInverse" value="1" />
							<label class="custom-control-label" for="headerInverse">&nbsp;</label>
						</div>
					</div>
				</div>
				<div class="row m-t-10">
					<div class="col-6 control-label text-inverse f-w-600">Sidebar Fixed</div>
					<div class="col-6 d-flex">
						<div class="custom-control custom-switch ml-auto">
							<input type="checkbox" class="custom-control-input" name="sidebar-fixed" id="sidebarFixed" value="1" checked />
							<label class="custom-control-label" for="sidebarFixed">&nbsp;</label>
						</div>
					</div>
				</div>
				<div class="row m-t-10">
					<div class="col-6 control-label text-inverse f-w-600">Sidebar Grid</div>
					<div class="col-6 d-flex">
						<div class="custom-control custom-switch ml-auto">
							<input type="checkbox" class="custom-control-input" name="sidebar-grid" id="sidebarGrid" value="1" />
							<label class="custom-control-label" for="sidebarGrid">&nbsp;</label>
						</div>
					</div>
				</div>
				<div class="row m-t-10">
					<div class="col-md-6 control-label text-inverse f-w-600">Sidebar Gradient</div>
					<div class="col-md-6 d-flex">
						<div class="custom-control custom-switch ml-auto">
							<input type="checkbox" class="custom-control-input" name="sidebar-gradient" id="sidebarGradient" value="1" />
							<label class="custom-control-label" for="sidebarGradient">&nbsp;</label>
						</div>
					</div>
				</div>
				<div class="divider"></div>

			</div>
		</div>
<!-- END THEME PANEL -->