admin_apps/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('the_applications.users.urls', 'login'), namespace='login')),
    path('users/', include(('the_applications.users.urls', 'users'), namespace='users')),
    path('settings/', include(('the_applications.general_settings.urls', 'general_settings'), namespace='settings')),
    path('apps/', include(('the_applications.applications.urls', 'apps'), namespace='apps')),
    path('notify/', include(('the_applications.notify.urls', 'notify'), namespace='notify')),
    path('data/', include(('the_applications.datasheet.urls', 'data'), namespace='data')),
    path('rules/', include(('the_applications.rules.urls', 'rules'), namespace='rules')),
    path('typetransport/', include(('the_applications.type_transport.urls', 'typetransport'), namespace='typetransport')),
    path('zones/', include(('the_applications.zones.urls', 'zones'), namespace='zones')),
    path('api/', include(('the_applications.api.urls', 'api'), namespace='api')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

the_applications/rules/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path(
        route='',
        view=views.Principal.as_view(),
        name=''
    ),
    path(
        route='model',
        view=views.Modelx.as_view(),
        name='model'
    ),
    path(
        route='model2',
        view=views.Modelx2.as_view(),
        name='model2'
    ),
    path(
        route='create',
        view=views.UpdateModel.as_view(),
        name='create'
    ),
    path(
        route='update_model',
        view=views.UpdateModel.as_view(),
        name='update_model'
    ),
    path(
        route='datatables_model',
        view=views.DatatablesModel.as_view(),
        name='datatables_model'
    ),
    path(
        route='delete_rules',
        view=views.DatatablesDeleteRules.as_view(),
        name='delete_rules'
    ),
    path(
        route='active_toggle_rules',
        view=views.DatatablesActiveToggleRules.as_view(),
        name='active_toggle_rules'
    ),
    path(
        route='showid',
        view=views.ShowId,
        name='showid'
    ),
    path(
        route='get_filedsmodel_id',
        view=views.PostGetFieldsModelId.as_view(),
        name='get_filedsmodel_id'
    )
]

the_applications/zones/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path(
        route='',
        view=views.Principal.as_view(),
        name=''
    ),
    path(
        route='edos',
        view=views.Estados.as_view(),
        name='edos'
    ),
    path(
        route='post_get_states',
        view=views.PostGetStates.as_view(),
        name='post_get_states'
    ),
    path(
        route='datatables_info_edos',
        view=views.DataTablesInfoEdos.as_view(),
        name='datatables_info_edos'
    ),
    path(
        route='datatables_info_model',
        view=views.DataTablesInfoModel.as_view(),
        name='datatables_info_model'
    ),
    path(
        route='showidedos',
        view=views.ShowIdEdos,
        name='showidedos'
    ),
    path(
        route='showidm',
        view=views.ShowIdModel,
        name='showidm'
    ),
    path(
        route='active_toggle_rules',
        view=views.DatatablesActiveToggleRules.as_view(),
        name='active_toggle_rules'
    ),
    path(
        route='active_toggle_rules_edos',
        view=views.DatatablesActiveToggleRulesEdos.as_view(),
        name='active_toggle_rules_edos'
    ),
    path(
        route='active_toggle_rules_model',
        view=views.DatatablesActiveToggleRulesModel.as_view(),
        name='active_toggle_rules_model'
    ),
    path(
        route='delete_rules',
        view=views.DatatablesDeleteRules.as_view(),
        name='delete_rules'
    ),
    path(
        route='delete_rules_edos',
        view=views.DatatablesDeleteRulesEdos.as_view(),
        name='delete_rules_edos'
    ),
    path(
        route='delete_rules_model',
        view=views.DatatablesDeleteRulesModel.as_view(),
        name='delete_rules_model'
    ),
    path(
        route='update_model_edos',
        view=views.UpdateModelEdos.as_view(),
        name='update_model_edos'
    ),
    path(
        route='update_model_model',
        view=views.UpdateModelModel.as_view(),
        name='update_model_model'
    )
]

the_applications/zones/models.py
from django.db import models


class Model(models.Model):
    name = models.CharField(max_length=200, default='')
    description = models.TextField()
    edos = models.CharField(max_length=200, default='')
    code = models.CharField(max_length=200, default='')
    number_code = models.IntegerField()
    active = models.SmallIntegerField(default=1)
    write_date = models.DateTimeField(auto_now_add=True)
    create_date = models.DateTimeField(auto_now_add=True)
    create_uid = models.IntegerField()
    write_uid = models.IntegerField()

class Edos(models.Model):
    name = models.CharField(max_length=200, default='')
    active = models.SmallIntegerField(default=1)
    write_date = models.DateTimeField(auto_now_add=True)
    create_date = models.DateTimeField(auto_now_add=True)
    create_uid = models.IntegerField()
    write_uid = models.IntegerField()

the_applications/zones/views.py
#django
from django.views.generic import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin
from the_applications.zones.forms import ModelForms as MF, EdosForms as ME, ModelForms2 as MFU
from the_applications.zones.models import Model as M, Edos as E
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect
from the_applications.notify.models import TypeNotify, Notify
from django.contrib.auth.decorators import login_required
# Model

class Principal(LoginRequiredMixin, TemplateView):
    template_name = 'zones/main.html'

    def post(self, request, *args, **kwargs):
        context = {
            'erros': []
        }
        response = {
            'data':[],
            'error': False,
            'msj':''
        }
        data = request.POST
        print("************************************ >")
        print(data)
        print("************************************ <")
        form = MF(data)
        if form.is_valid():
            name = data["name"]
            form.save(user=request.user.id)
            type_notify = TypeNotify.objects.get(pk=1)
            new_notify = Notify(
                user=request.user,
                type=type_notify,
                name="Nuevo Estado - {}".format(str(name)),
                description="""
                                                       El usuario "{} {}"  ha generado un nuevo Estado 
                                                        con identificador "{}". Ya puede ser utilizado para los modelos 
                                                        de evaluación del sitema dentro de las condiciones.  
                                                       """.format(request.user.first_name,
                                                                  request.user.last_name,
                                                                  str(name)),
                priority=1,
                picture='notify/pictures/camion.png'
            )
            new_notify.save()
            response['msj'] = "Se ha registrado el nuevo transporte con éxito. Folio {}".format(name)
        else:
            response['error'] = True
            response['msj'] = str(form.errors)
        context['form'] = form
        context['response'] = response
        return render(
            request,
            'zones/main.html',
            context,
        )

    def get_context_data(self, **kwargs):
        context2 = super().get_context_data(**kwargs)
        form1 = MF()
        form2 = ME()
        context2['form1'] = form1
        context2['form2'] = form2
        context2['name_model'] = "Zonas"
        context2['name_model2'] = "Estados"
        return context2

class Estados(LoginRequiredMixin, TemplateView):
    template_name = 'zones/main.html'

    def post(self, request, *args, **kwargs):
        context = {
            'erros': []
        }
        response = {
            'data':[],
            'error': False,
            'msj':''
        }
        data = request.POST
        form = ME(data)
        if form.is_valid():
            name = data["name"]
            form.save(user=request.user.id)

            type_notify = TypeNotify.objects.get(pk=1)
            new_notify = Notify(
                user=request.user,
                type=type_notify,
                name="Nuevo Estado - {}".format(str(name)),
                description="""
                                                       El usuario "{} {}"  ha generado un nuevo estado
                                                        con nombre "{}". Ya puede ser utilizado para los modelos
                                                        de evaluación del sitema dentro de las condiciones.
                                                       """.format(request.user.first_name,
                                                                  request.user.last_name,
                                                                  str(name)),
                priority=1,
                picture='notify/pictures/edos.png'
            )
            new_notify.save()
            response['msj'] = "Se ha registrado el nuevo transporte con éxito. Folio {}".format(name)
        else:
            response['error'] = True
            response['msj'] = str(form.errors)
        context['form'] = form
        context['response'] = response
        return render(
            request,
            'zones/main.html',
            context,
        )

class PostGetStates(LoginRequiredMixin, TemplateView):
    template_name = 'zones/main.html'


    def post(self, request, *args, **kwargs):

        query = E.objects.all().values()
        response = {
            'data':[],
            'error': False,
            'msj':''
        }
        data = []
        for q in query:
            item = {
                'id': q["id"],
                'name': q["name"],
                'active': q["active"],
            }
            data.append(item)
        response['data']=data
        return JsonResponse(response)

    def get_context_data(self, context, **kwargs):
        context2 = super().get_context_data(**kwargs)
        return context2


class DataTablesInfoEdos(LoginRequiredMixin, TemplateView):
    template_name = 'zones/main.html'


    def post(self, request, *args, **kwargs):

        query = E.objects.all().values()
        response = {
            'data':[],
            'error': False,
            'msj':''
        }
        data = []
        for q in query:
            item = {
                'id': q["id"],
                'name': q["name"],
                'active': q["active"],
            }
            data.append(item)
        response['data']=data
        return JsonResponse(response)

    def get_context_data(self, context, **kwargs):
        context2 = super().get_context_data(**kwargs)
        return context2

class DataTablesInfoModel(LoginRequiredMixin, TemplateView):
    template_name = 'zones/main.html'


    def post(self, request, *args, **kwargs):

        query = M.objects.all().values()
        response = {
            'data':[],
            'error': False,
            'msj':''
        }
        data = []
        for q in query:
            item = {
                'id': q["id"],
                'name': q["name"],
                'description': q["description"],
                'edos': q["edos"],
                'code': q["code"],
                'number_code': q["number_code"],
                'active': q["active"],
            }
            data.append(item)
        response['data']=data
        return JsonResponse(response)

    def get_context_data(self, context, **kwargs):
        context2 = super().get_context_data(**kwargs)
        return context2


class UpdateModelEdos(LoginRequiredMixin, TemplateView):
    template_name = 'zones/main.html'

    def post(self, request, *args, **kwargs):
        context2 = {
            'erros': []
        }
        response = {
            'data': [],
            'error': False,
            'msj': ''
        }
        data = request.POST
        print("#########################")
        print(data)
        form = ME(data)
        if form.is_valid():
            name = data["name"]
            form.write(request.user.id)
            type_notify = TypeNotify.objects.get(pk=1)
            new_notify = Notify(
                user=request.user,
                type=type_notify,
                name="Actualización de Estado - {}".format(str(name)),
                description="""
                           El usuario "{} {}"  ha actualizado el estado
                            con nombre "{}". Ya puede ser utilizado para los modelos
                            de evaluación del sitema dentro de las condiciones.
                           """.format(request.user.first_name,
                                      request.user.last_name,
                                      str(name)),
                priority=1,
                picture='notify/pictures/edos.png'
            )
            new_notify.save()
            response['msj'] = "Se ha actualizado '{}' correctamente".format(data['name'])
        else:
            response['msj'] = "Ha ocurrido un error al querer Guardar el dato '{}'".format(data['name'])
        context2['response'] = response
        return render(
            request,
            'zones/main.html',
            context2,
        )
class UpdateModelModel(LoginRequiredMixin, TemplateView):
    template_name = 'zones/main.html'

    def post(self, request, *args, **kwargs):
        context2 = {
            'erros': []
        }
        response = {
            'data': [],
            'error': False,
            'msj': ''
        }
        data = request.POST
        print("######################### :v")
        print(data)
        form = MFU(data)
        print("~~~~~~~~~~~")
        print(form)
        print("~~~~~~~~~~~")
        if form.is_valid():
            print("~~~~~~~~~~~ ****")
            name = data["name"]
            print("~~~~~~~~~~~ ****")
            form.write(request.user.id)
            type_notify = TypeNotify.objects.get(pk=1)
            new_notify = Notify(
                user=request.user,
                type=type_notify,
                name="Actualización de Zona - {}".format(str(name)),
                description="""
                                       El usuario "{} {}"  ha actualizado la zona
                                        con nombre "{}". Ya puede ser utilizado para los modelos
                                        de evaluación del sitema dentro de las condiciones.
                                       """.format(request.user.first_name,
                                                  request.user.last_name,
                                                  str(name)),
                priority=1,
                picture='notify/pictures/zone.png'
            )
            new_notify.save()

templates/zones/showmodel.html
{% extends 'base.html' %}
{% load static %}

{% block sitio %}
    <li class="breadcrumb-item"><a href="{% url 'zones:' %}">Zonas</a></li>
    <li class="breadcrumb-item"><a href="">{{ name }}</a></li>
{% endblock %}


{% block content %}
{% csrf_token %}
<!-- begin row -->
<h3>Zona ({{ name }})</h3><br>
<div class="row">
    <div class="col-md-12">
        <div class="panel panel-inverse">
            <div class="panel-heading">
                <h4 class="panel-title">.</h4>
                <div class="panel-heading-btn">
                    <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-default" data-click="panel-expand"><i class="fa fa-expand"></i></a>
                    <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-success" data-click="panel-reload"><i class="fa fa-redo"></i></a>
                    <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-warning" data-click="panel-collapse"><i class="fa fa-minus"></i></a>
                    <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-danger" data-click="panel-remove"><i class="fa fa-times"></i></a>
                </div>
            </div>
            <div class="panel-body m-20">
                 <div class="row">
                     <div class="col-12 m-b-30" >
                         <div class="card" style="padding: 30px;border: none !important;">
                             <div class="cpage-card" style="display: block;">
                                <div class="lphead">
                                    <a class="rew-btn" href="{% url 'zones:' %}" ><iconify-icon style="font-size: 14px;" icon="solar:multiple-forward-left-bold-duotone"></iconify-icon>Volver</a>
                                </div>
                                 <div class="lpbody">
                                    <style>
                                         .helptext{top: 5px !important;}
                                    </style>
                                    <form id="act-model" action="{% url 'zones:update_model_model' %}" method="post">
                                        {% csrf_token %}
                                        {{ form }}
                                        <br>
                                        <input class="btn btn-success" type="submit" value="Actualizar">
                                     </form>
                                 </div>
                             </div>
                         </div>
                     </div>

                </div>
            </div>
        </div>
    </div>
</div>
<!-- end row -->
<!-- begin row -->

{% endblock %}

{% block style %}
    <style>
    .rc-id{
        display:none;
    }
    .btn-name-mdl-create{
        font-size: 14px;
    }
    .chip-user{
        width: 100%;
        text-align: center;
    }
    .bold{
        font-weight: bold !important;
        color:#0d3349;
    }
    .badge{
        background: transparent !important;
    }
    .lphead{
        margin-bottom: 20px !important;
    }
    .state-li{
        color: #000000;
        border: 1px solid #00000038;
        background: #c6c6c6;
        display: inline-block;
        min-width: 100px;
        max-width: 100px;
        padding: 4px 10px;
        text-align: center;
        border-radius: 5px;
    }
    .state-as{
        color: #ffffff;
        border: 1px solid #00000038;
        background: #009688;
        display: inline-block;
        min-width: 100px;
        max-width: 100px;
        padding: 4px 10px;
        text-align: center;
        border-radius: 5px;
    }
    .state-an{
        color: #ffffff;
        border: 1px solid #00000038;
        background: #03A9F4;
        display: inline-block;
        min-width: 100px;
        max-width: 100px;
        padding: 4px 10px;
        text-align: center;
        border-radius: 5px;
    }
    .state-cl{
        color: #000000;
        border: 1px solid #00000038;
        background: #ffb64c;
        display: inline-block;
        min-width: 100px;
        max-width: 100px;
        padding: 4px 10px;
        text-align: center;
        border-radius: 5px;
    }
    .state-ap{
        color: #ffffff;
        border: 1px solid #00000038;
        background: #4CAF50;
        display: inline-block;
        min-width: 100px;
        max-width: 100px;
        padding: 4px 10px;
        text-align: center;
        border-radius: 5px;
    }
    .state-o-cp{
        color: #ffffff;
        border: 1px solid #00000038;
        background: #8859db;
        display: inline-block;
        min-width: 100px;
        max-width: 100px;
        padding: 4px 10px;
        text-align: center;
        border-radius: 5px;
    }
    .state-o-ca{
        color: #ffffff;
        border: 1px solid #00000038;
        background: #22c4b5;
        display: inline-block;
        min-width: 100px;
        max-width: 100px;
        padding: 4px 10px;
        text-align: center;
        border-radius: 5px;
    }
    .state-f-fs{
        color: #ffffff;
        border: 1px solid #00000038;
        background: #e44949;
        display: inline-block;
        min-width: 100px;
        max-width: 100px;
        padding: 4px 10px;
        text-align: center;
        border-radius: 5px;
    }
    table.dataTable.cell-border>tbody>tr>* {
        border-right: none !important;
    }
    table.dataTable.cell-border>tbody>tr>*:first-child {
        border-left: none !important;
    }
    table.dataTable.display tbody tr:hover.selected > .sorting_1, table.dataTable.order-column.hover tbody tr:hover.selected > .sorting_1 {
        box-shadow: inset 0 0 0 9999px rgb(255, 245, 220) !important;
    }
    table.dataTable.stripe > tbody > tr:nth-child(odd).selected > *, table.dataTable.display > tbody > tr:nth-child(odd).selected > * {
        box-shadow: inset 0 0 0 9999px rgb(255, 245, 220) !important;
    }
    table.dataTable.display > tbody > tr.selected + tr.selected > td {
        box-shadow: inset 0 0 0 9999px rgb(255, 245, 220) !important;
    }
    table.dataTable.display > tbody > tr.selected:hover > * {
        box-shadow: inset 0 0 0 9999px rgb(255, 245, 220) !important;
    }
    table.dataTable.display > tbody tr.selected > .sorting_1{
        box-shadow: inset 0 0 0 9999px rgb(255, 245, 220) !important;
    }
    table.dataTable.hover > tbody > tr.selected:hover > *, table.dataTable.display > tbody > tr.selected:hover > * {
      box-shadow: inset 0 0 0 9999px rgb(255, 245, 220) !important;
    }
    table.dataTable.stripe > tbody > tr:nth-child(odd).selected > *, table.dataTable.display > tbody > tr:nth-child(odd).selected > * {
      box-shadow: inset 0 0 0 9999px rgb(255, 245, 220) !important;
    }
    .rc-endpoint, .rc-file, .rc-external, .rc-internal {
        display: none;
    }
    .add-fields--internal input, .add-fields--external input, .add-fields--file input{
        height: 35.3px;
    }
    #edos-z-collector{
        display: block;
        width: 100%;
        height: calc(1.5em + .875rem + 2px);
        padding: .4375rem .75rem;
        font-size: .8125rem;
        font-weight: 400;
        line-height: 1.5;
        color: #212121;
        background-color: #fff;
        background-clip: padding-box;
        border: 1px solid #ccc;
        border-radius: 3px;
        transition: border-color .15s ease-in-out, box-shadow .15s ease-in-out;
    }
    .edos-append{
        display: block;
        position: relative;
        float: left;
        background: #d0d0d0;
        padding: 2px 10px;
        margin: 0px 5px;
        border-radius: 4px;
        font-weight: 700;
    }
    .edos-append a{
        background: #626262;
        margin-left: 8px;
        padding: 2px 5px;
        font-size: 8px;
        color: #dcdcdc !important;
        border-radius: 50%;
        margin-top: 2px;
        display: block;
        position: relative;
        float: right;
        cursor: pointer;
    }
    .badge.edos{
        color: #ffffff;
        border-radius: 0px;
        font-size: 14px;
        padding: 8px 8px;
        margin: 2px;
    }
    </style>
{% endblock %}

{% block script %}
<script>
    $(document).ready(function (){
        $("[for=id_id]").hide();
        if('{{ first }}' == 'True'){
            $('.errorlist').remove();
        }
        {% if response.error == True  %}
            Swal.fire({
                html: '<iconify-icon style="color:#f44336" class="icon-swal" icon="solar:dislike-bold-duotone"></iconify-icon><br><br><b><h3><b>Oopps !!</b></h3></b><h5>{{ response.msj }}</h5>',
                icon: "error",
                showCancelButton: false,
                confirmButtonBackground: "#009688",
                confirmButtonText: "Enterado"
            }).then((result) => {
              if (result.isConfirmed) {
                  window.location.href = "{% url 'typetransport:' %}";
              }
            });
        {% elif response.error == False %}
            Swal.fire({
                html: '<iconify-icon style="color:#4caf50" class="icon-swal" icon="solar:like-bold-duotone"></iconify-icon><br><br><b><h3><b>Genial!!</b></h3></b><h5>{{ response.msj }}</h5>',
                icon: "success",
                showCancelButton: false,
                confirmButtonBackground: "#009688",
                confirmButtonText: "Enterado"
            }).then((result) => {
              if (result.isConfirmed) {
                  window.location.href = "{% url 'typetransport:' %}";
              }
            });
        {% endif %}
        ///////////////////////////////////////////////////////////////////////////////////
        var az = $(".edos-z");
        var bz = $("#edos-z-collector");
        $("#edos-z-contain").remove();
        az.hide();
        $.post(
            "{% url "zones:post_get_states" %}",
            {'csrfmiddlewaretoken':csrfmiddlewaretoken}
        ).done(function (data){
            console.log("********************* >");
            var word = az.val();
            var word_split = word.split(",");
            var selecthtml = "<option></option>";
            for(var i = 0 ; i < (data.data).length ; i ++){
                selecthtml = selecthtml + '<option>['+data.data[i]["id"]+'] - '+data.data[i]["name"]+'</option>';
            }
            var htmlc = "";
            for(var j=0; j<word_split.length; j++){
                for(var k = 0 ; k < (data.data).length ; k ++){
                    if((parseInt(data.data[k]["id"])) == (parseInt(word_split[j]))){
                        console.log("---->  **** " + data.data[k]["name"]);
                        htmlc = htmlc + '<div id="edos-append-'+data.data[k]["id"]+'" class="edos-append" data-id="'+data.data[k]["id"]+'" data-name="'+data.data[k]["name"]+'"><span>'+data.data[k]["name"]+'</span><a class="clear-edos" data-id="edos-append-'+data.data[k]["id"]+'">X</a></div>';
                    }
                }
            }
            az.after('<div id="edos-z-contain" class="col-12" style="width: 100%;height: 70px;padding-left: 0px;padding-right: 0px;"><div id="edos-z-collector" class="col-12" style="float:left; margin-bottom: 5px;"></div><select id="edos-selected" class="form-control col-3" style="float:left;">'+selecthtml+'</select><i class="fa fa-globe" style="font-size: 20px;margin-left: 5px;margin-top: 8px;color: #cecece;"></i></div>');
            $("#edos-z-collector").append(htmlc);
            $("#edos-selected").change(function(){
                var sel = $("#edos-selected option:selected").text();
                var idz = sel.split("]")[0].split("[")[1]
                var namez = sel.split("-")[1].trim(" ");
                $("#edos-z-collector").append('<div id="edos-append-'+idz+'" class="edos-append" data-id="'+idz+'" data-name="'+namez+'"><span>'+namez+'</span><a class="clear-edos" data-id="edos-append-'+idz+'">X</a></div>');
                console.log(sel);
                $(".clear-edos").click(function(){
                    var dom = $(this).attr("data-id");
                    $("#"+dom).remove();
                    //////////
                    var collector = $("#edos-z-collector").children();
                    idsz = "";
                    for(var j = 0 ; j < collector.length ; j ++){
                        var dataId = $("#"+collector[j].id).attr("data-id");
                        idsz = idsz + "," + dataId;
                    }
                    idsz = idsz.substring(1, idsz.length);
                    console.log(idsz);
                    $("#id_edos").val(idsz);
                    /////////
                });
                //////////
                var collector = $("#edos-z-collector").children();
                idsz = "";
                for(var j = 0 ; j < collector.length ; j ++){
                    var dataId = $("#"+collector[j].id).attr("data-id");
                    idsz = idsz + "," + dataId;
                }
                idsz = idsz.substring(1, idsz.length);
                console.log(idsz);
                $("#id_edos").val(idsz);
                /////////
            });
            console.log("********************* <");
        });
        ///////////////////////////////////////////////////////////////////////////////////
    });

</script>
{% endblock%}
